animes/urls.py
from django.urls import path
from . import views 
from .views import (
    HomeView,
    AnimeView,
    SeasonView,
    EpisodeView,
    SearchView
)
app_name = 'animes' 
urlpatterns = [
    path('', HomeView.as_view(), name='series'),
    path('seasons/<slug>/', AnimeView.as_view(), name='seasons'),
    path('episodes/<slug>/', SeasonView.as_view(), name='episodes'),
    path('download/<slug>/', EpisodeView.as_view(), name='episode'),
    path('search/', SearchView.as_view(), name='search'),
    path('genre/<slug:slug>/', views.genre_list, name='genre_list'),
    path("alphasearch/", views.search_abc_list, name='searchlist'),
]

mortalflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myflix.urls')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('series/', include('tvseries.urls', namespace='tvseries')),
    path('animes/', include('animes.urls', namespace='animes')), 
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views 
from .views import (
    HomeView,
    MovieView,
    SearchView
)
app_name = 'movies' 
urlpatterns = [
    path('', HomeView.as_view(), name='movies'),
    path('download/<slug>/', MovieView.as_view(), name='movie'),
    path('search/', SearchView.as_view(), name='search'),
    path('genre/<slug:slug>/', views.genre_list, name='genre_list'),
    path("alphasearch/", views.search_abc_list, name='searchlist'),
]

myflix/urls.py
from django.contrib.auth import views as auth_views
# from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views 
from .views import (
    HomeView,
    SearchView,
    RegisterView,
    ProfileView,
    LoginView
)
app_name = 'myflix' 
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path("alphasearch/", views.search_abc_list, name='searchlist'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

animes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
CATEGORY = (
    ('B', 'Bollywood'),
    ('C', 'Chinese'),
    ('F', 'French'),
    ('G', 'German'),
    ('Go', 'Gollywood'),
    ('H', 'Hollywood'),
    ('J', 'Japanese'),
    ('K', 'Korean'),
    ('N', 'Nollywood'),
    ('S', 'Spanish')
)

LABEL = (
    ('L', 'Latest'),
    ('R', 'Recently Released'),
    ('S', 'Coming Soon'),
    ('T', 'Top Rated'),
)

TAG = (
    ('N', 'New'),
    ('SP', 'Season Priemere'),
    ('SF', 'Season Finale'),
)

FORMAT = (
    ('MP4', 'Mp4'),
    ('3GP', '3gp'),
    ('HD', 'High Definition'),
)

class Genre(models.Model):
  title= models.CharField(max_length=200, unique=True)
  slug= models.SlugField(max_length=200, unique=True)
  created_on= models.DateTimeField(auto_now_add=True)
  updated_on= models.DateTimeField(auto_now=True)

  # def cat(self):
  #   return self.title

  class Meta:
    """docstring for Meta"""
    ordering = ['-created_on']

  def __str__(self):
    return self.title

  # def get_absolute_url(self):
  #   return reverse('category:category_detail', args=[self.slug])

class Anime(models.Model):
  title= models.CharField(max_length=200, unique=True)
  slug= models.SlugField(max_length=200, unique=True)
  category = models.CharField(choices=CATEGORY, max_length=2)
  # genre = models.CharField(max_length=200, default="", blank=True)
  runtime = models.CharField(max_length=200, default="", blank=True)
  label = models.CharField(choices=LABEL, max_length=2)
  description = models.TextField()
  avatar = models.ImageField(upload_to='images/avatar', default=None)
  adlink= models.URLField(max_length=200, default="", blank=True)
  created_on= models.DateTimeField(auto_now_add=True)
  updated_on= models.DateTimeField(auto_now=True)

  genres = models.ManyToManyField(Genre, related_name='series')


  class Meta:
    """docstring for Meta"""
    ordering = ['-created_on']

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('animes:seasons', kwargs={"slug" : self.slug})
  
  @property
  def no_of_comments(self):
    return Comment.objects.filter(anime=self).count()

class Season(models.Model) :
  anime = models.ForeignKey(Anime, default="", on_delete=models.CASCADE)
  title= models.CharField(max_length=200, unique=True)
  slug= models.SlugField(max_length=200, unique=True)
  # slug = AutoSlugField(populate_from='title', unique_with='created_on')
  tag = models.CharField(choices=TAG, max_length=2)
  adlink= models.URLField(max_length=200, default="", blank=True)
  created_on= models.DateTimeField(auto_now_add=True, null=True)
  updated_on= models.DateTimeField(auto_now=True, null=True)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("animes:episodes", kwargs={
        "slug" : self.slug
    
    })
  
  @property
  def no_of_comments(self):
    return Comment.objects.filter(season=self).count()

class Episode(models.Model) :
  anime = models.ForeignKey(Anime, default="", on_delete=models.CASCADE)
  season = models.ForeignKey(Season, on_delete=models.CASCADE)
  title= models.CharField(max_length=200, unique=True)
  description = models.TextField(default="", blank=True)
  slug= models.SlugField(max_length=200, unique=True)
  tag = models.CharField(choices=TAG, max_length=2)
  adlink= models.URLField(max_length=200, default="", blank=True)
  created_on= models.DateTimeField(auto_now_add=True, null=True)
  updated_on= models.DateTimeField(auto_now=True, null=True)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("animes:episode", kwargs={
        "slug" : self.slug
    
    })
  
  @property
  def no_of_comments(self):
    return Comment.objects.filter(episode=self).count()

class Download(models.Model) :
  anime = models.ForeignKey(Anime, default="", on_delete=models.CASCADE)
  season = models.ForeignKey(Season, on_delete=models.CASCADE)
  episode = models.ForeignKey(Episode, on_delete=models.CASCADE)
  title= models.CharField(max_length=200, unique=True)
  link= models.URLField(max_length=200, unique=True)
  mediaformat= models.CharField(choices=FORMAT, max_length=3)
  created_on= models.DateTimeField(auto_now_add=True, null=True)
  updated_on= models.DateTimeField(auto_now=True, null=True)

  def __str__(self):
    return self.title

class Trailer(models.Model):
  title= models.CharField(max_length=200)
  imagelink = models.URLField(max_length=200, default="", blank=True)
  link= models.URLField(max_length=200, unique=True)
  release_date= models.DateField(null=True)
  created_on= models.DateTimeField(auto_now_add=True, null=True)
  updated_on= models.DateTimeField(auto_now=True, null=True)

  def __str__(self):
    return self.title

class Comment(models.Model) :
  anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
  season = models.ForeignKey(Season, on_delete=models.CASCADE)
  episode = models.ForeignKey(Episode, on_delete=models.CASCADE)
  name= models.CharField(max_length=200)
  email= models.EmailField(max_length=200)
  phone= models.CharField(max_length=200)
  content = models.TextField()
  created_on= models.DateTimeField(auto_now_add=True, null=True)
  updated_on= models.DateTimeField(auto_now=True, null=True)

  def __str__(self):
    return self.name

animes/views.py
import string
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.views.generic import ListView, DetailView
from .models import (                           
    Anime,
    Season,
    Episode,
    Download,
    Comment,
    Genre,
    Trailer
)

alphabet = string.ascii_uppercase

# Create your views here.
class HomeView(ListView):
    model = Anime
    context_object_name = 'series'
    template_name = "animes.html"
    extra_context={'alphabet': alphabet}
    ordering = ['created_on']
    paginate_by = 6

    def get_context_data(self,*args, **kwargs): 
        context = super(HomeView, self).get_context_data(*args,**kwargs) 
        context['episodes']= Episode.objects.order_by('-created_on')[:10]
        context['atrailers']= Trailer.objects.order_by('-created_on')[:8]

        list_series = Anime.objects.all()
        paginator = Paginator(list_series, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_series = paginator.page(page)
        except PageNotAnInteger:
            file_series = paginator.page(1)
        except EmptyPage:
            file_series = paginator.page(paginator.num_pages)
            
        context['list_series'] = file_series

        return context

class AnimeView(DetailView):
    Model = Anime
    context_object_name = 'seasons'
    template_name = "animes_season_lists.html"
    queryset = Anime.objects.all()

    def get_context_data(self, **kwargs):
        self.anime = get_object_or_404(Anime, slug=self.kwargs['slug'])
        context = super(AnimeView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        seasons = paginator = Paginator(Season.objects.filter(anime=self.anime).order_by('created_on'), 10)
        context['seasons'] = seasons.get_page(page)
        context['series'] = Anime.objects.all()
        return context

class SeasonView(DetailView):
    context_object_name = 'episodes'
    template_name = "animes_episode_lists.html"
    queryset = Season.objects.all()

    def get_context_data(self, **kwargs):
        self.season = get_object_or_404(Season, slug=self.kwargs['slug'])
        context = super(SeasonView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        episodes = paginator = Paginator(Episode.objects.filter(season=self.season).order_by('created_on'), 10)
        context['episodes'] = episodes.get_page(page)
        return context

class EpisodeView(DetailView):
    context_object_name = 'episode'
    template_name = "animes_download.html"
    queryset = Episode.objects.all()

    def get_context_data(self, **kwargs):
        self.episode = get_object_or_404(Episode, slug=self.kwargs['slug'])
        context = super(EpisodeView, self).get_context_data(**kwargs)
        context['episode'] = Download.objects.filter(episode=self.episode)
        context['comments'] = Comment.objects.filter(episode=self.episode).order_by('-created_on')
        return context
    
    def post(self, request, *args,**kwargs):
        self.episode = get_object_or_404(Episode, slug=self.kwargs['slug'])
        new_comment = Comment(content=request.POST.get('content'),
                            name = request.POST.get('name'),
                            email = request.POST.get('email'),
                            phone = request.POST.get('phone'),
                            episode = self.get_object(),
                            season = Season.objects.get(episode=self.episode),
                            anime = Anime.objects.get(episode=self.episode)
        )
        new_comment.save()
        return self.get(self, request, *args, **kwargs)

class SearchView(ListView):
    model = Anime
    template_name = "search_series.html"
    extra_context={'alphabet': alphabet}

    def get_queryset(self):
        query = self.request.GET.get('search')
        filter_field = self.request.GET.get('filter_field')
        
        if query is not None:
            lookups= Q(title__icontains=query) & Q(category__icontains=filter_field)

            results= Anime.objects.filter(lookups).distinct()

            return results

        else:
            return Anime.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search'] = {
            'search': self.request.GET.get('search', ''),
            'filter_field': self.request.GET.get('filter_field', '')
        }

        return context

def genre_list(request, slug):
  series = Anime.objects.filter(
      genres__slug__contains=slug
  ).order_by('-created_on').distinct()

  genres = Genre.objects.all()
  genre_row = Genre.objects.filter(slug=slug)

  context = {'slug': slug, 'gen': genre_row, 'series': series, 'genres': genres }
  return render(request, 'animes_genre.html', context)

def search_abc_list(request):
    series = Anime.objects.all()
    # context_object_name = 'searchlist'
    
    if request.method == 'GET':
        query= request.GET.get('list')

        if query is not None:

            if query in alphabet.upper():
                lookups= Q(title__startswith=query)

                results= Anime.objects.filter(lookups).distinct()

                context={'results': results, 'series': series, 'alphabet': alphabet}

                return render(request, 'animes_abc_list.html', context)

            else:
                
                lookups= Q(title__regex =r'^\d[\w\d _-]+')
                # lookups= Q(title__startswith = 2)

                results= Anime.objects.filter(lookups).distinct()

                context={'results': results, 'series': series}

                return render(request, 'series_abc_list.html', context)

        else:
            return render(request, 'series_abc_list.html')

    else:
        return render(request, 'series_abc_list.html')

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="zxx">
	
<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Mortalflix - Online Movie, Video, Anime, TV  Series and Shows Download</title>
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'img/favcion.png' %}" />
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" media="all" />
		<!-- Slick nav CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.min.css' %}" media="all" />
		<!-- Iconfont CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/icofont.css' %}" media="all" />
		<!-- Owl carousel CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
		<!-- Popup CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
		<!-- Main style CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="all" />
		<!-- Responsive CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" media="all" />
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!-- Page loader -->
	    <div id="preloader"></div>
		<!-- header section start -->
		<header class="header">
			<div class="container">
				<div class="header-area">
					<div class="logo">
						<a href="/"><img src="{% static 'img/logo5.png' %}" alt="logo" /></a>
					</div>
					<div class="menu-area">
						<div class="responsive-menu"></div>
					    <div class="mainmenu">
                            <ul id="primary-menu">
                                <li><a class="active" href="/">Home</a></li>
                                <li><a href="{% url 'movies:movies' %}">Movies</a></li>
								<li><a href="{% url 'tvseries:series' %}">Tvseries</a></li>
                                <!-- <li><a href="celebrities.html">CelebritiesList</a></li> -->
                                <li><a href="{% url 'animes:series' %}">Animes</a></li>
                                <li><a href="blog.html">News</a></li>
								<!-- <li><a href="#">Pages <i class="icofont icofont-simple-down"></i></a>
									<ul>
										<li><a href="blog-details.html">Blog Details</a></li>
										<li><a href="movie-details.html">Movie Details</a></li>
									</ul>
								</li> -->
                                <!-- <li><a class="theme-btn" href="#"><i class="icofont icofont-ticket"></i> Tickets</a></li> -->
                            </ul>
					    </div>
					</div>
					<div class="header-right">
                        {% if appname == 'tvseries' %}
                            <form action="{% url 'tvseries:search' %}" method="GET">
								<select name="filter_field">
                                    {% if request.GET.filter_field == 'H' %}
                                        <option value="H" selected>Hollywood</option>
                                    {% else %}
                                        <option value="H">Hollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'N' %}
                                        <option value="N" selected>Nollywood</option>
                                    {% else %}
                                        <option value="N">Nollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'B' %}
                                        <option value="B" selected>Bollywood</option>
                                    {% else %}
                                        <option value="B">Bollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'K' %}
                                        <option value="K" selected>Korean</option>
                                    {% else %}
                                        <option value="K">Korean</option>
                                    {% endif %}
                                </select>
                        {% elif appname == 'movies' %}
                            <form action="{% url 'movies:search' %}" method="GET">
								<select name="filter_field">
                                    {% if request.GET.filter_field == 'H' %}
                                        <option value="H" selected>Hollywood</option>
                                    {% else %}
                                        <option value="H">Hollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'N' %}
                                        <option value="N" selected>Nollywood</option>
                                    {% else %}
                                        <option value="N">Nollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'B' %}
                                        <option value="B" selected>Bollywood</option>
                                    {% else %}
                                        <option value="B">Bollywood</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'K' %}
                                        <option value="K" selected>Korean</option>
                                    {% else %}
                                        <option value="K">Korean</option>
                                    {% endif %}
                                </select>
                        {% elif appname == 'animes' %}
                            <form action="{% url 'animes:search' %}" method="GET">
								<select name="filter_field">  
									{% if request.GET.filter_field == 'H' %}
                                        <option value="H" selected>Hollywood</option>
                                    {% else %}
                                        <option value="H">Hollywood</option>
                                    {% endif %}                                  
                                    {% if request.GET.filter_field == 'J' %}
                                        <option value="J" selected>Japanese</option>
                                    {% else %}
                                        <option value="J">Japanese</option>
                                    {% endif %}
                                </select>
                        {% else %}
                            <form action="{% url 'myflix:search' %}" method="GET">
                                <select name="filter_field">
                                    {% if request.GET.filter_field == 'Series' %}
                                        <option value="Series" selected>Tvseries</option>
                                    {% else %}
                                        <option value="Series">Tvseries</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'Movie' %}
                                        <option value="Movie" selected>Movies</option>
                                    {% else %}
                                        <option value="Movie">Movie</option>
                                    {% endif %}
                                    {% if request.GET.filter_field == 'Anime' %}
                                        <option value="Anime" selected>Animes</option>
                                    {% else %}
                                        <option value="Anime">Animes</option>
                                    {% endif %}
                                </select>
						{% endif %}
                                
                                <input type="text" name="search" value="{{request.GET.search}}" />
                                <button><i class="icofont icofont-search"></i></button>
                            </form>
						<ul>
							{% if request.user.is_authenticated %}
							<li><a href="{% url 'myflix:profile' pk=request.user.id %}">Welcome {{ request.user.username }}!</a></li>
							<li><a class="" href="{% url 'myflix:logout' %}">Logout</a></li>
							{% else %}
							<li><a class="signup-popup" href="#">Signup</a></li>
							<li><a class="login-popup" href="#">Login</a></li>
							{% endif %}
						</ul>
					</div>					
				</div>
			</div>

			{% for message in messages %}
				{% if 'login' in message.tags %}
					<div class="alert alert-info">{{message}}</div>
				{% endif %}
			{% endfor %}

			{% for message in messages %}
				{% if 'register' in message.tags %}
					<div class="alert alert-info">{{message}}</div>
				{% endif %}
			{% endfor %}
		</header>
		<div class="login-area" id="signup-area">
			<div class="login-box">
				<a href="#"><i class="icofont icofont-close"></i></a>
				<h2>CREATE ACCOUNT</h2>
				<form action="{% url 'myflix:register' %}" method="POST">
					{% csrf_token %}
					<h6>USERNAME</h6>
					<input type="text" name="username" />
					<h6>EMAIL ADDRESS</h6>
					<input type="email" name="email" />
					<h6>PASSWORD</h6>
					<input type="password" name="password" />
					<div class="login-remember">
						<input type="checkbox" />
						<span>Remember Me</span>
					</div>
					<div class="login-signup">
						<!-- <span>SIGNUP</span> -->
						<a class="login-popup" href="#">Login</a>
					</div>
					<button type="submit" class="theme-btn">Signup</button>
					<span>Or Via Social</span>
					<div class="login-social">
						<a href="#"><i class="icofont icofont-social-facebook"></i></a>
						<a href="#"><i class="icofont icofont-social-twitter"></i></a>
						<a href="#"><i class="icofont icofont-social-linkedin"></i></a>
						<a href="#"><i class="icofont icofont-social-google-plus"></i></a>
						<a href="#"><i class="icofont icofont-camera"></i></a>
					</div>
				</form>
				
			</div>
		</div>
		<div class="login-area" id="login-area">
			<div class="login-box">
				<a href="#"><i class="icofont icofont-close"></i></a>
				<h2>LOGIN</h2>
				<form action="{% url 'myflix:login' %}" method="POST">
					{% csrf_token %}
					<h6>USERNAME OR EMAIL ADDRESS</h6>
					<input type="text" name="username" />
					<h6>PASSWORD</h6>
					<input type="password" name="password" />
					<div class="login-remember">
						<input type="checkbox" />
						<span>Remember Me</span>
					</div>
					<div class="login-signup">
						<!-- <span>SIGNUP</span> -->
						<a class="signup-popup" href="#">Signup</a>
					</div>
					<button type="submit" class="theme-btn">LOG IN</button>
					<span>Or Via Social</span>
					<div class="login-social">
						<a href="#"><i class="icofont icofont-social-facebook"></i></a>
						<a href="#"><i class="icofont icofont-social-twitter"></i></a>
						<a href="#"><i class="icofont icofont-social-linkedin"></i></a>
						<a href="#"><i class="icofont icofont-social-google-plus"></i></a>
						<a href="#"><i class="icofont icofont-camera"></i></a>
					</div>
				</form>
				
			</div>
		</div><!-- header section end -->

{% block content %}
{% endblock content %}

{% include "footer.html" %}


{% include "script.html" %}

{% block extra_script %}
{% endblock extra_script %}

</body>

</html>

templates/episode_lists.html
{% extends 'base.html' %}
{% load static %}
{% static 'images' as baseUrl %}

{% block content %}

<!-- breadcrumb area start -->
<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-area-content">
                    <!-- <h1>{{ object.series.title }}: {{ object.title }}</h1> -->
                    <h1>{{ object.title }}</h1>
                </div>
            </div>
        </div>
    </div>
</section><!-- breadcrumb area end -->
<!-- blog area start -->
<section class="blog-details">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="news-details">
                    <div class="single-news">
                        <div style="background: url('{{ object.series.avatar.url }}'), url('{{ object.series.avatar.url }}');
                        background-repeat: no-repeat;
                        background-position: center;
                        background-size: contain, cover;
                        height: 350px;"></div>
                        <div class="news-date">
                            <h2><span>{{ object.series.created_on|date:'M' }}</span> {{ object.series.created_on|date:'d' }}</h2>
                            <h1>{{ object.series.created_on|date:'Y' }}</h1>
                        </div>
                    </div>
                    <h2>{{ object.title }}</h2>
                    <i class="icofont icofont-tags">
                        {% for genre in object.series.genres.all %}
                        <a href="{% url 'tvseries:genre_list' genre.slug  %}">{{ genre.title}}{% if not forloop.last %}, {% endif %}</a>
                        {% endfor %}
                    </i> | <i class="icofont icofont-time" title="runtime"> <span>{{ object.series.runtime }}</span></i> | 
                    <a href="#"><i class="icofont icofont-comment"></i>{{ object.no_of_comments }} Comment{{ object.no_of_comments|pluralize }}</a>
                    <!-- <a href="#"><i class="icofont icofont-comment"></i>1k Comments</a> -->
                    <p>{{ object.series.description }}</p>
                    <div class="text-center">
                        <img src="{% static 'img/blog-detail.png' %}" alt="" />
                    </div>
                    <div class="details-reply">
                        <h2>Episodes</h2>
                        <ul>
                            {% for episode in episodes %}
                            <hr/>
                            <li class="pt-2 pb-2">
                                <a class="font-lite-black" href="{% url 'tvseries:episode' episode.slug  %}">{{ episode.title }}</a>
                            </li>
                            {% empty %}
                            <p>Episodes not available here yet :(</p>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="details-thumb">
                        {% if episodes.has_previous %}
                        <div class="details-thumb-prev">
                            <div class="thumb-icon">
                                {% for episode in episodes %}
                                <a href="/series/episodes/{{episode.season.slug}}/?page={{ episodes.previous_page_number }}"><i class="icofont icofont-simple-left"></i></a>
                                {% endfor %}
                            </div>
                            <div class="thumb-text">
                                <h4>Previous List</h4>
                                <p>Page {{ episodes.number }} of {{ episodes.paginator.num_pages }}.</p>
                            </div>
                        </div>
                        {% else %}
                        <div class="details-thumb-prev">
                            <div class="thumb-icon"></div>
                        </div>
                        {% endif %}
                        {% if episodes.has_next %}
                        <div class="details-thumb-next">
                            <div class="thumb-text">
                                <h4>Next List</h4>
                                <p>Page {{ episodes.number }} of {{ episodes.paginator.num_pages }}.</p>
                            </div>
                            <div class="thumb-icon">
                                {% for episode in episodes %}
                                <a href="/series/episodes/{{episode.season.slug}}/?page={{ episodes.next_page_number }}"><i class="icofont icofont-simple-right"></i></a>
                                {% endfor %}
                            </div>
                        </div>
                        {% else %}
                        <div class="details-thumb-next">
                            <div class="thumb-icon"></div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- blog area end -->


{% endblock content %}